# Generated by Django 4.1.9 on 2023-06-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author", models.CharField(max_length=200)),
                (
                    "stars",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 estrella"),
                            (2, "2 estrellas"),
                            (3, "3 estrellas"),
                            (4, "4 estrellas"),
                            (5, "5 estrellas"),
                        ],
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
