# Generated by Django 4.1.9 on 2023-07-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="size",
            field=models.IntegerField(choices=[(1, "Pequeño"), (2, "Mediano"), (3, "Grande")], default=1),
            preserve_default=False,
        ),
    ]
