# Generated by Django 4.1.9 on 2023-06-29 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("service", "0001_initial"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=10, null=True)),
                ("date_of_event", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("people", models.IntegerField()),
                ("budget", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("quote_by_phone", models.BooleanField(default=False)),
                ("quote_by_email", models.BooleanField(default=True)),
                ("quote_by_sms", models.BooleanField(default=False)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="location.location")),
                ("service", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="service.service")),
            ],
        ),
    ]
