# Generated by Django 4.1.9 on 2023-07-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_alter_servicedetail_size"),
        ("quote", "0003_quote_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="service",
        ),
        migrations.AddField(
            model_name="quote",
            name="service_detail",
            field=models.ManyToManyField(to="service.servicedetail"),
        ),
    ]
