# Generated by Django 4.1.9 on 2023-07-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote", "0005_remove_quote_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="total_service",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
