# Generated by Django 4.1.9 on 2023-07-07 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("theme", "0001_initial"),
        ("quote", "0006_quote_total_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="theme",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="theme.theme"),
        ),
    ]
