# Generated by Django 4.1.9 on 2023-07-07 20:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quote", "0007_quote_theme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quote",
            name="budget",
        ),
    ]
