# Generated by Django 4.1.9 on 2023-07-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0002_location_size"),
        ("quote", "0009_alter_quote_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="location",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="location.location"
            ),
        ),
    ]
