# Generated by Django 4.1.9 on 2023-07-07 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("quote", "0008_remove_quote_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("transport", models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ("iva", models.IntegerField(choices=[(0, "0"), (1, "5"), (2, "10"), (3, "15")])),
                ("discount", models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ("message", models.TextField(blank=True)),
                ("quote", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="quote.quote")),
            ],
        ),
    ]
