# Generated by Django 4.1.9 on 2023-07-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_pdf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotedetail",
            name="discount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="quotedetail",
            name="transport",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
