# Generated by Django 4.1.9 on 2023-07-07 21:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("quote_pdf", "0002_alter_quotedetail_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotedetail",
            name="created_date",
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
