# Generated by Django 4.1.9 on 2023-07-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_pdf", "0003_quotedetail_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotedetail",
            name="update_date",
            field=models.DateField(auto_now=True),
        ),
    ]
