# Generated by Django 4.1.9 on 2023-07-09 22:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quote_pdf", "0005_alter_quotedetail_discount_alter_quotedetail_iva_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotedetail",
            name="iva",
            field=models.DecimalField(
                choices=[
                    (Decimal("0.0"), "0"),
                    (Decimal("0.05"), "5"),
                    (Decimal("0.10"), "10"),
                    (Decimal("0.15"), "15"),
                ],
                decimal_places=2,
                max_digits=8,
            ),
        ),
    ]
