# Generated by Django 4.1.9 on 2023-07-09 23:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("quote_pdf", "0007_quotedetail_folio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotedetail",
            name="folio",
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
