# Generated by Django 4.1.9 on 2023-06-29 21:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=40)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50), blank=True, null=True, size=None
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="service_images")),
                ("location", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("size", models.IntegerField(choices=[(1, "Pequeño"), (2, "Mediano"), (3, "Grande")])),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("duration", models.DurationField(blank=True, null=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_details",
                        to="service.service",
                    ),
                ),
            ],
        ),
    ]
