# Generated by Django 4.1.9 on 2023-07-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedetail",
            name="size",
            field=models.IntegerField(choices=[(0, "No service"), (1, "Pequeño"), (2, "Mediano"), (3, "Grande")]),
        ),
    ]
