# Generated by Django 4.1.9 on 2023-07-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_alter_servicedetail_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedetail",
            name="size",
            field=models.IntegerField(choices=[(0, "Personalizado"), (1, "Pequeño"), (2, "Mediano"), (3, "Grande")]),
        ),
    ]
