# Generated by Django 4.1.9 on 2023-07-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0003_alter_servicedetail_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicedetail",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="servicedetail",
            name="size",
            field=models.IntegerField(choices=[(0, "Unico"), (1, "Pequeño"), (2, "Mediano"), (3, "Grande")]),
        ),
    ]
